function  Data = buildData_kalman(rawData,altitude)
Long = rawData.Longitude;
Lat = rawData.Latitude;
Alt = ones(size(rawData,1),1)*altitude;
AccX = rawData.AccX;
AccY = rawData.AccY;
AccZ = rawData.AccZ;
[Roll,Pitch] = FindAngleKalman(rawData.gyro_x,rawData.gyro_y,rawData.gravity_x,rawData.gravity_y,rawData.gravity_z);
Yaw = deg2rad(rawData.Heading);
Data = table(Long,Lat,Alt,AccX,AccY,AccZ,Roll,Pitch,Yaw);