function EulerAngle = kalman_innovate(kalman,z1,z2)
z = [z1;z2];
kalman.x = kalman.F*kalman.x;
kalman.P = kalman.F*kalman.P*kalman.F.' + kalman.Q;
y = z - kalman.H*kalman.x;
S = kalman.H*kalman.P*kalman.H.' + kalman.R;
K = kalman.P*kalman.H.'/S;
kalman.x = kalman.x + K*y;
kalman.P = (eye(3)-K*kalman.H)*kalman.P;
EulerAngle = kalman.x(1);